import type { Metadata, Viewport } from "next";
import {
  Geist,
  Geist_Mono,
  Andika,
  BioRhyme,
  DotGothic16,
} from "next/font/google";
import "./globals.css";
import Menu from "./feat/menu/menu";

/// Fonts

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const andika = Andika({
  variable: "--font-andika",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const bioRhyme = BioRhyme({
  variable: "--font-bio-rhyme",
  subsets: ["latin"],
});

const dotGothic16 = DotGothic16({
  variable: "--font-dot-gothic-16",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "PENFRIENDS",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${andika.variable} ${bioRhyme.variable} ${dotGothic16.variable} antialiased`}
      >
        {/* Global Header */}
        <header className="flex justify-between items-center px-6 py-10 h-10 bg-">
          {/* Hamburger Menu */}
          <Menu />
          {/* Title */}
          <div className="flex items-center justify-center">
            <h1
              className="title text-center font-extrabold text-base sm:text-xl lg:text-2xl"
              style={{ fontFamily: "var(--font-bio-rhyme)" }}
            >
              PENFRIENDS
            </h1>
          </div>
          {/* Account Icon */}
          <div className="flex items-center">
            <img
              src="/account.png"
              alt="Account"
              className="w-10 h-10 rounded-full cursor-pointer hover:scale-125 transition-transform duration-300"
            />
          </div>
        </header>

        {/* Page Content */}
        {children}
      </body>
    </html>
  );
}
